{% set name = "shtab" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d923ce349fe1dca87d4f94c01b361a9642de606ed4cc8df0fd496c8253cd6d6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shtab = shtab.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shtab
  commands:
    - shtab -h
    - shtab -u shtab.main.get_main_parser

about:
  home: https://github.com/iterative/shtab
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE
  summary: Automatically generate shell tab completion scripts for python CLI apps

  description: |
    - What: Automatically generate shell tab completion scripts for python CLI apps
    - Why: Speed & correctness. Alternatives like `argcomplete` & `pyzshcomplete` are slow and have side-effects
    - How: `shtab` processes an `argparse.ArgumentParser` object to generate a tab completion script for your shell

extra:
  recipe-maintainers:
    - casperdcl
    - efiop
    - shcheklein
