{% set name = "shtab" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49dd9689a1a0492b1e93cc2900fe14e02df89c54b0ce65d033f511fe6b5dd0b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shtab = shtab.main:main

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=2.7

test:
  imports:
    - shtab
  commands:
    - shtab -h
    - shtab -u shtab.main.get_main_parser

about:
  home: https://github.com/iterative/shtab
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE
  summary: Automatically generate shell tab completion scripts for python CLI apps
  description: |
    - What: Automatically generate shell tab completion scripts for python CLI apps
    - Why: Speed & correctness. Alternatives like `argcomplete` & `pyzshcomplete` are slow and have side-effects
    - How: `shtab` processes an `argparse.ArgumentParser` object to generate a tab completion script for your shell

extra:
  recipe-maintainers:
    - casperdcl
    - efiop
    - shcheklein
